name: Tests and Code Coverage for the nanites package

on: [push]

jobs:
  run:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]

    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
      USING_COVERAGE: '3.8'

    steps:

      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test and generate coverage report
        run: |
          pip install pytest
          pytest

      - name: Convert coverage
        run: python -m coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
